on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-22.04
    name: OTP 27 / Elixir 1.18
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout ${{github.repository}}
        uses: actions/checkout@v4
      - name: Checkout sqltest
        uses: actions/checkout@v4
        with:
            path: sqltest
            repository: elliotchance/sqltest
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27
          elixir-version: 1.18
      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - run: mix deps.get && mix sql.gen.test sqltest/standards/2016 && mix test
